### ISSUE TITLE
parrot-menu/desktop-files binary names point to incorrect locations

### ISSUE THREAD

**Issue by ingochris** [ParrotSec/parrot-menu#10]
From GitLab:

> Some of parrot tools are not running which includes
> Parrot>Vulnerability Analysis>Stress Testing> denial6,dhcpig,dos-new-ip6,flood-advertise6,flood_dhcp6,flood_mld26,flood_mld6 and many more

Hi @PalinuroSec,

I took a brief look into this issue - it is due to the application desktop files pointing to incorrect locations. Take flood_mld26, for instance:

```bash
parrot# cat /usr/share/applications/parrot-flood_mld6.desktop
[Desktop Entry]
Name=flood_mld6
Encoding=UTF-8
Exec=menuexec flood_mld6 
Icon=parrot-menu.png
StartupNotify=false
Terminal=true
Type=Application
Categories=02-07-stress-testing;03-09-ipv6
X-Parrot-Package=thc-ipv6


parrot# menuexec atk6-flood_mld6                          
 ____                      _   ____       
|  _ \ __ _ _ __ _ __ ___ | |_/ ___|  ___  ___ 
| |_) / _` | '__| '__/ _ \| __\___ \ / _ \/ __|
|  __/ (_| | |  | | | (_) | |_ ___) |  __/ (__ 
|_|   \__,_|_|  |_|  \___/ \__|____/ \___|\___|
                                               

executing "atk6-flood_mld6"

atk6-flood_mld6 v3.0 (c) 2015 by van Hauser / THC <vh@thc.org> www.thc.org

Syntax: atk6-flood_mld6 interface [target]

Flood the local network with MLD reports.


parrot# menuexec flood_mld6
 ____                      _   ____       
|  _ \ __ _ _ __ _ __ ___ | |_/ ___|  ___  ___ 
| |_) / _` | '__| '__/ _ \| __\___ \ / _ \/ __|
|  __/ (_| | |  | | | (_) | |_ ___) |  __/ (__ 
|_|   \__,_|_|  |_|  \___/ \__|____/ \___|\___|
                                               

executing "flood_mld6"

sudo: flood_mld6: command not found
parrot# 

```

I could write an easy test suite for the menu applications, but ideally I think this should be fixed at the root cause (on the menu update side). As I've only done a brief investigation of the issue and haven't gone through the codebase to see how updates are managed, please advise.

May The Force Be With You,
Christopher Ngo

**Comment by PalinuroSec** [comment]
the thc-ipv6 package have been updated and its binaries have changed their names, this is the cause of the problem

anyways we don't use github anymore, the whole discussion and the pull requests should be done on https://dev.parrotsec.org/parrot/parrot-menu

p.s.
thanks for your help
