### ISSUE TITLE
menuexecg don't start program (NO ROOT)

### ISSUE THREAD

**Issue by Kounty2Rolen** [ParrotSec/parrot-menu#12]
if I start the program through menuexecG then it does not start, but if through menuexec then it starts with output to the console, What's the problem
[SCREENSHOT's]
https://b.radikal.ru/b02/1712/c9/ca410816abc2.png

https://b.radikal.ru/b05/1712/19/e0d89991a533.png

[VIDEO]
https://youtu.be/dzr4CFzV3Ns

**Comment by PalinuroSec** [comment]
dist-upgrade your system and try to use menuexecg with a gui application

try something like 

menuexecg wireshark

on a dist-upgraded version of parrot and let me know if it works

also make sure to have gksu installed
